version: "3"

services:
    postgres:
        image: postgres:12.3-alpine
        volumes:
            - pq_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db

    go_app:
        image: golang:1.14.4-alpine
        volumes: 
            - .:/go/src/github.com/polipopoliko/todo/todo2
        working_dir: /go/src/github.com/polipopoliko/todo/todo2
        depends_on: 
            - postgres
        command: go run main.go

    adminer:
        image: adminer
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pgsql
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DEFAULT_USER: postgres
            ADMINER_DEFAULT_PASSWORD: password
volumes:
    pq_data: {}