version: "3"

services:
    postgres:
        image: postgres:12.3-alpine
        volumes:
            - pq_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db

    go:
        image: go_db:latest
        build: $GOPATH/src/github.com/polipopoliko/todo/todo2
        depends_on: 
            - postgres
        command: go run main.go
volumes:
    pq_data: {}